on:
  push:
    branch: develop
jobs:
  build:
    defaults:
      run:
        working-directory: ./cat
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: make s21_cat
  test:
    defaults:
      run:
        working-directory: ./.github/workflows/test_scripts/cat
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - run: bash test.sh
  style:
    defaults:
      run:
        shell: bash
        working-directory: ./.github/workflows/test_scripts/cat
    runs-on: macos-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v1
      - run: brew install clang-format
      - run: bash style.sh